"""Remove tag field from Task model

Revision ID: 57552a66c594
Revises: bb0b8a166721
Create Date: 2024-02-29 12:28:26.625723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57552a66c594'
down_revision = 'bb0b8a166721'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('tag')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tag', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
